import Game from '@/scripts/rules'
import { createStore } from 'vuex'
import { EMPTY_TERRAIN, TERRAIN, FORTRESS_1, FORTRESS_2, NO_PAWN, PAWN_1, PAWN_2 } from '@/scripts/consts'

export default createStore({
  state: {
    game: new Game(
      [
        [FORTRESS_2, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN],
        [TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, EMPTY_TERRAIN],
        [TERRAIN, TERRAIN, TERRAIN, TERRAIN, EMPTY_TERRAIN, TERRAIN],
        [TERRAIN, TERRAIN, EMPTY_TERRAIN, TERRAIN, TERRAIN, TERRAIN],
        [TERRAIN, EMPTY_TERRAIN, TERRAIN, TERRAIN, EMPTY_TERRAIN, TERRAIN],
        [TERRAIN, TERRAIN, TERRAIN, EMPTY_TERRAIN, TERRAIN, TERRAIN],
        [TERRAIN, EMPTY_TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN],
        [EMPTY_TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN],
        [TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, FORTRESS_1]
      ],
      [
        [NO_PAWN, PAWN_2, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN],
        [PAWN_2, PAWN_2, PAWN_2, NO_PAWN, NO_PAWN, NO_PAWN],
        [NO_PAWN, PAWN_2, PAWN_2, NO_PAWN, NO_PAWN, NO_PAWN],
        [NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN],
        [NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN],
        [NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN],
        [NO_PAWN, NO_PAWN, NO_PAWN, PAWN_1, PAWN_1, NO_PAWN],
        [NO_PAWN, NO_PAWN, NO_PAWN, PAWN_1, PAWN_1, PAWN_1],
        [NO_PAWN, NO_PAWN, NO_PAWN, NO_PAWN, PAWN_1, NO_PAWN]
      ],
      9
    ),
    round: 0
  },
  getters: {
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
